# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           pretty
#relative_permalinks: false

# Setup
tagline:               Byrney
title:             'Reluctantly Enterprising'
description:       'Reluctantly Enterprising'
url:
baseurl:             ""
paginate:            5

# About/contact
author:
  name:              Robert Byrne
  url:               http://github.com/byrney
  email:

# Custom vars
version:             1.0.0
